#include <shared/AetherShaderTypes.h>

#include <cstddef>

static_assert(sizeof(AetherFullscreenVertex) == 16);
static_assert(sizeof(AetherPresentationUniforms) == 16);
static_assert(sizeof(AetherGaussianCompositionUniforms) == 160);
static_assert(sizeof(AetherProxyGpuVertex) == 32);
static_assert(offsetof(AetherProxyGpuVertex, normalPadding) == 16);
static_assert(sizeof(AetherProxyUniforms) == 144);
static_assert(offsetof(AetherProxyUniforms, previousViewProjection) == 64);
static_assert(offsetof(AetherProxyUniforms, options) == 128);
static_assert(sizeof(AetherBloomUniforms) == 16);
static_assert(sizeof(AetherTemporalUniforms) == 144);
static_assert(sizeof(AetherGizmoUniforms) == 112);
static_assert(offsetof(AetherFullscreenVertex, position) == 0);
static_assert(offsetof(AetherFullscreenVertex, uv) == 8);
static_assert(offsetof(AetherMeshVertex, position) == 0);
static_assert(offsetof(AetherMeshVertex, normal) == 16);
static_assert(offsetof(AetherMeshVertex, tangent) == 32);
static_assert(offsetof(AetherMeshVertex, textureCoordinate) == 48);
static_assert(offsetof(AetherMeshVertex, joints) == 64);
static_assert(offsetof(AetherMeshVertex, weights) == 80);
static_assert(sizeof(AetherJointMatrix) == 128);
static_assert(sizeof(AetherSkinDraw) == 16);
static_assert(sizeof(AetherMorphDelta) == 48);
static_assert(sizeof(AetherMorphDraw) == 16);
static_assert(sizeof(AetherMaterialUniforms) == 224);
static_assert(sizeof(AetherFrameUniforms) == 448);
static_assert(offsetof(AetherFrameUniforms, view) == 64);
static_assert(offsetof(AetherFrameUniforms, normalTransform) == 192);
static_assert(offsetof(AetherFrameUniforms, cameraPosition) == 256);
static_assert(offsetof(AetherFrameUniforms, drawIds) == 304);
static_assert(offsetof(AetherFrameUniforms, previousViewProjection) == 320);
static_assert(offsetof(AetherFrameUniforms, previousModel) == 384);
static_assert(sizeof(AetherGpuLight) == 64);
static_assert(sizeof(AetherLightCluster) == 8);
static_assert(sizeof(AetherClusterUniforms) == 32);
static_assert(sizeof(AetherIblUniforms) == 16);
static_assert(sizeof(AetherShadowUniforms) == 304);
static_assert(sizeof(AetherLocalShadowUniforms) == 1136);
static_assert(offsetof(AetherMaterialUniforms, textureFlags) == 48);
static_assert(offsetof(AetherMaterialUniforms, uvScaleOffset) == 64);
static_assert(offsetof(AetherMaterialUniforms, uvRotation) == 144);
static_assert(sizeof(AetherGaussianGpu) == 256);
static_assert(offsetof(AetherGaussianGpu, shRest) == 64);
static_assert(sizeof(AetherGaussianCamera) == 144);
static_assert(offsetof(AetherGaussianCamera, tileGridCounts) == 96);
static_assert(offsetof(AetherGaussianCamera, cameraWorldPosition) == 112);
static_assert(offsetof(AetherGaussianCamera, debugOptions) == 128);
static_assert(sizeof(AetherProjectedGaussian) == 80);
static_assert(offsetof(AetherProjectedGaussian, tileBounds) == 48);
static_assert(sizeof(AetherGaussianCounters) == 16);
static_assert(sizeof(AetherTsdfVoxelGpu) == 32);
static_assert(offsetof(AetherTsdfVoxelGpu, observations) == 20);
static_assert(sizeof(AetherTsdfFrameUniforms) == 128);
static_assert(offsetof(AetherTsdfFrameUniforms, worldToCameraQuaternion) == 64);
static_assert(offsetof(AetherTsdfFrameUniforms, gridDimensionsBlock) == 96);
