#!/usr/bin/env python3
"""Create a manuscript-safe reviewer-v2 LaTeX block from frozen audit results.

The bridge is fail-closed for claims:
- reviewerEvidenceReady=false -> emit comments/status only, no compiled claim text;
- reviewerEvidenceReady=true  -> emit a self-contained Results subsection and copy
  frozen reviewer figures into researchpaper/figures for manuscript inclusion.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    out = text
    for old, new in replacements.items():
        out = out.replace(old, new)
    return out


def copy_if_present(source: Path, destination: Path) -> bool:
    if not source.is_file():
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    return True


def build_open_tex(audit: dict[str, Any]) -> str:
    gates = audit.get("readinessGates", {})
    open_gates = sorted(name for name, passed in gates.items() if not passed)
    lines = [
        "% AUTO-GENERATED BY cbrc_reviewer_manuscript_block.py",
        "% reviewerEvidenceReady=false: no reviewer-v2 manuscript claims emitted.",
        f"% recordCount={audit.get('recordCount', 0)}",
        f"% certifiedNonzeroLocalCases={audit.get('certifiedNonzeroLocalCases', 0)}",
        f"% toleranceCrossoverGroups={audit.get('toleranceCrossoverGroups', 0)}",
        "% open gates: " + ", ".join(open_gates),
        "% Preserve this negative result; do not retune the frozen protocol post hoc.",
        "",
    ]
    return "\n".join(lines)


def build_ready_tex(
    audit: dict[str, Any],
    *,
    have_real_scene: bool,
    have_crossover: bool,
) -> str:
    datasets = audit.get("nonzeroLocalDatasets", [])
    dataset_text = ", ".join(latex_escape(str(x)) for x in datasets)
    nonzero = int(audit.get("certifiedNonzeroLocalCases", 0))
    local = int(audit.get("localCases", 0))
    full = int(audit.get("fullFallbackCases", 0))
    crossovers = int(audit.get("toleranceCrossoverGroups", 0))
    near = int(audit.get("nearBoundaryLocalCases", 0))
    partial = int(audit.get("certifiedPartialRepairCases", 0))
    records = int(audit.get("recordCount", 0))
    repair_violations = int(audit.get("repairCertificateViolationCount", 0))
    cert_violations = int(audit.get("certificateViolationCount", 0))

    lines = [
        "% AUTO-GENERATED BY cbrc_reviewer_manuscript_block.py",
        r"\subsection{Certified non-zero residual stress test}",
        (
            f"A separately frozen reviewer-v2 campaign executes {records} partial-repair "
            f"stress cases. {partial} cases exercise the certified omitted-Gaussian "
            f"repair mode. The run produces {local} \\LOCAL{{}} decisions and {full} "
            f"\\FULL{{}} fallbacks, including {nonzero} certified \\LOCAL{{}} cases "
            f"with a measured non-zero residual that still satisfies "
            f"$0<E_q^{{\\mathrm{{full-ref}}}}\\leq B_q(C)\\leq\\varepsilon_q$. "
            f"We observe {cert_violations} core-certificate violations and "
            f"{repair_violations} omitted-subset certificate violations."
        ),
        (
            f"The audit identifies {near} near-boundary \\LOCAL{{}} cases and "
            f"{crossovers} fixed-edit tolerance-crossover groups. Certified non-zero "
            f"\\LOCAL{{}} cases occur across {len(datasets)} datasets"
            + (f" ({dataset_text})." if datasets else ".")
            + " Source state, edit, camera, history, work model, and omitted-subset rule "
              "remain fixed within each crossover group; epsilon is the only swept input."
        ),
    ]

    if have_real_scene:
        lines.extend(
            [
                r"\begin{figure*}[t]",
                r"  \centering",
                r"  \includegraphics[width=\textwidth]{figures/reviewer_v2_real_scene.png}",
                r"  \caption{Reviewer-v2 captured-scene evidence. Captured source context is shown beside the evaluated before state, certified partial repair, independent \FULL{} result, residual, and certified support. Source imagery and oracle imagery are labeled separately; pixel registration is claimed only where established by the benchmark provenance.}",
                r"  \label{fig:reviewer-v2-real}",
                r"\end{figure*}",
            ]
        )

    if have_crossover:
        lines.extend(
            [
                r"\begin{figure*}[t]",
                r"  \centering",
                r"  \includegraphics[width=\textwidth]{figures/reviewer_v2_crossover.png}",
                r"  \caption{Fixed-edit tolerance crossover from the frozen reviewer-v2 protocol. The physical edit and all scene state remain unchanged while epsilon varies, exposing the transition between fail-closed \FULL{} and certified \LOCAL{} selection.}",
                r"  \label{fig:reviewer-v2-crossover}",
                r"\end{figure*}",
            ]
        )

    lines.append("")
    return "\n\n".join(lines)


def build_status_md(audit: dict[str, Any]) -> str:
    gates = audit.get("readinessGates", {})
    lines = [
        "# Reviewer-v2 manuscript bridge",
        "",
        f"- reviewerEvidenceReady: **{audit.get('reviewerEvidenceReady', False)}**",
        f"- Records: **{audit.get('recordCount', 0)}**",
        f"- Certified partial-repair cases: **{audit.get('certifiedPartialRepairCases', 0)}**",
        f"- Certified non-zero LOCAL: **{audit.get('certifiedNonzeroLocalCases', 0)}**",
        f"- Near-boundary LOCAL: **{audit.get('nearBoundaryLocalCases', 0)}**",
        f"- Tolerance crossover groups: **{audit.get('toleranceCrossoverGroups', 0)}**",
        f"- Core certificate violations: **{audit.get('certificateViolationCount', 0)}**",
        f"- Partial-repair certificate violations: **{audit.get('repairCertificateViolationCount', 0)}**",
        "",
        "## Gates",
        "",
    ]
    for name, passed in gates.items():
        lines.append(f"- {'PASS' if passed else 'OPEN'} — {name}")
    lines.extend(
        [
            "",
            "If any gate is OPEN, the LaTeX bridge contains comments only and the "
            "manuscript makes no reviewer-v2 success claim. Preserve the frozen run "
            "instead of deleting cases or retuning epsilon.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--audit", type=Path, required=True)
    parser.add_argument("--visual-dir", type=Path, required=True)
    parser.add_argument("--repo-root", type=Path, required=True)
    args = parser.parse_args()

    audit_path = args.audit.resolve()
    visual_dir = args.visual_dir.resolve()
    repo = args.repo_root.resolve()
    audit = load_json(audit_path)

    generated_dir = repo / "researchpaper/generated"
    figures_dir = repo / "researchpaper/figures"
    generated_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    tex_path = generated_dir / "reviewer_v2_results.tex"
    status_path = generated_dir / "reviewer_v2_status.md"

    ready = bool(audit.get("reviewerEvidenceReady", False))
    have_real_scene = False
    have_crossover = False

    if ready:
        have_real_scene = copy_if_present(
            visual_dir / "F_REVIEWER_REAL_SCENE_LOCAL_VS_FULL.png",
            figures_dir / "reviewer_v2_real_scene.png",
        )
        have_crossover = copy_if_present(
            visual_dir / "F_REVIEWER_TOLERANCE_CROSSOVER.png",
            figures_dir / "reviewer_v2_crossover.png",
        )
        tex = build_ready_tex(
            audit,
            have_real_scene=have_real_scene,
            have_crossover=have_crossover,
        )
    else:
        tex = build_open_tex(audit)

    tex_path.write_text(tex, encoding="utf-8")
    status_path.write_text(build_status_md(audit), encoding="utf-8")

    print(
        json.dumps(
            {
                "reviewerEvidenceReady": ready,
                "tex": str(tex_path),
                "status": str(status_path),
                "copiedRealSceneFigure": have_real_scene,
                "copiedCrossoverFigure": have_crossover,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
