if(NOT DEFINED FASTGLTF_SOURCE_DIR)
    message(FATAL_ERROR "FASTGLTF_SOURCE_DIR is required")
endif()

set(source_file "${FASTGLTF_SOURCE_DIR}/src/fastgltf.cpp")
file(READ "${source_file}" source)
set(broken "if (weightsError != Error::None) {\n\t            node.weights")
set(fixed "if (weightsError == Error::None) {\n                node.weights")
string(FIND "${source}" "${fixed}" fixed_position)
if(NOT fixed_position EQUAL -1)
    message(STATUS "fastgltf node.weights parser fix is already present")
    return()
endif()

string(FIND "${source}" "${broken}" broken_position)
if(broken_position EQUAL -1)
    message(FATAL_ERROR "fastgltf node.weights patch context does not match pinned source")
endif()
string(REPLACE "${broken}" "${fixed}" patched "${source}")
file(WRITE "${source_file}" "${patched}")
message(STATUS "Applied fastgltf node.weights parser fix")
